config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'
  get 'about', to: 'static_pages#about'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  namespace :api do
    resources :users, only: [:show, :update, :index, :destroy]
    resources :images, only: [:create, :show, :index]
    resources :image_likes, only: [:create]
    resources :user_views, only: [:create]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :ensure_session_token

  validates :email, :username, :password_digest, :session_token, uniqueness: true, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}
  validates :skill_type, inclusion: { in: ["Photographer", "Model"] }
  validates :gender, inclusion: { in: ["Male", "Female"] }
  validates :city, presence: { message: " is invalid" }

  has_many :user_views

  has_many :images

  has_many :image_likes, foreign_key: :liker_id

  has_many :liked_images, through: :image_likes, source: :image

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_unique_token
    self.save!
    self.session_token
  end

  def generate_unique_token
    pass_digest = SecureRandom.urlsafe_base64

    while User.exists?(session_token: pass_digest)
      pass_digest = SecureRandom.urlsafe_base64
    end

    pass_digest
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/models/user_view.rb
class UserView < ActiveRecord::Base
  validates :user_id, presence: true

  belongs_to :user
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def index
    if params[:your_city]
      @users = User.joins('LEFT OUTER JOIN user_views ON users.id = user_views.user_id')
       .where("city = ? AND guest = false", current_user.city)
       .order("COUNT(user_views.id) desc")
       .group("users.id")
       .limit(20)
    elsif params[:city]
      @users = User.joins('LEFT OUTER JOIN user_views ON users.id = user_views.user_id')
       .where("city = ? AND guest = false", params[:city])
       .order("COUNT(user_views.id) desc")
       .group("users.id")
       .limit(20)
    else
      @users = User.joins(:user_views)
        .where("guest = false")
        .order("COUNT(user_views.id) desc")
        .group("users.id")
        .limit(20)
    end

    render 'api/users/index.json.jbuilder'
  end

  def show
    if params[:username]
      @user = User.where("username = '#{params[:username]}'").first
    else
      @user = User.find(params[:id])
    end

    render 'api/users/show.json.jbuilder'
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      render json: @user
    else
      render json: "OOOHHH NNEEEWW", status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      render json: @user
    else
      render json: {}, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :email,
        :username,
        :password,
        :skill_type,
        :gender,
        :city,
        :about_me,
        :experience,
        :compensation,
        :avatar_img
      )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render 'users/new'
  end

  def create
    @user = User.new(user_params)
    @user.city = Geocoder.address(@user.city)

    if @user.save
      login!(@user)
      redirect_to root_url
    else
      flash.now[:error] = @user.errors.full_messages
      render 'users/new'
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :email,
        :username,
        :password,
        :skill_type,
        :gender,
        :city,
        :avatar_img
      )
    end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/views/users/new.html.erb
<div class="form-container">
  <form id="new-user-form" action="<%= users_url %>" method="post">
    <div class="error-box">
      <% if flash.now[:error] %>
        <ul>
          <% flash.now[:error].each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <img src="https://www.filepicker.io/api/file/q49noi2xQdqHLKhRIxxo">

    <h6>New Account</h6>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>
      Email<br>
      <input type="text" name="user[email]" value="<%= @user.email %>">
    </label><br>

    <label>
      Username<br>
      <input type="text" name="user[username]" value="<%= @user.username %>">
    </label><br>

    <label>
      Password<br>
      <input type="password" name="user[password]">
    </label><br>

    <label>
      Skill Type<br>
      <select name="user[skill_type]">
        <option value="Photographer">Photographer</option>
        <option value="Model">Model</option>
      </select>
    </label>

    <label>
      Gender<br>
      <select name="user[gender]">
        <option value="Male">Male</option>
        <option value="Female">Female</option>
      </select>
    </label><br><br>

    <label>
      City<br>
      <input type="text" name="user[city]" id="searchTextField">
    </label><br><br>

    <input class="submit" type="submit" value="Sign Up">
    <br>
    <a class="switch-link" href="/session/new">Log In</a>
    <br><br>
    <%= button_to "About", about_url, class: "about", method: :get %>
  </form>
</div>

<div class="about-container">
  <div class="about-section">
    <h5>What is model findr about?</h5>
    <p>
      <span class="description-text">
        <span class="fancy-text">model findr</span> is about connecting the people who love the camera to the
        people who love taking pictures. Here at <span class="fancy-text">model findr</span> we want it
        so that you will have to look no farther than your own computer to discover
        aesthetically talented people. Whether it be photographer or model, both are here.
      </span>
    </p><br><br><hr>

    <p>
      <span class="disclaimer-text">
        <strong>DISCLAIMER:</strong>
        Most of these photos have been taken from the internet, this is a project
        from <span class="fancy-text-name">YS Productions</span> (Yusuf Soomro Productions).
        I am <strong>NOT</strong> in any way an owner of these photos. The people
        in the images include: Mario Testino, Jennifer Lawrence, Ben Stiller,
        Bruce Weber, Adam Gallagher, Mikki Koomar, Scarlet Johansson,
        Scott Eastwood, Juergen Teller, Terry Richardson, Godfrey Gao,
        Kylie Jenner, and Lupita Nyong'o.
      </span>
    </p>
  </div>
</div>


<script charset="utf-8">
  function initialize() {
    var options = {
      types: ['(cities)'],
      componentRestrictions: {country: "us"}
    };

    var input = document.getElementById('searchTextField');
    var autocomplete = new google.maps.places.Autocomplete(input, options);
  }

  initialize()

  $('.about').on('click', function(event) {
    event.preventDefault();
    $('.about-section').css("display", "block")
  })
</script>